update conda dir permissions

diff --git a/build/debian/init-apt-deps b/build/debian/init-apt-deps
--- a/build/debian/init-apt-deps
+++ b/build/debian/init-apt-deps
@@ -4,8 +4,8 @@
 # ==========================
 
 err_exit() {
-    echo "# !Error: $*"
-    exit 1
+	echo "# !Error: $*"
+	exit 1
 }
 
 set -e
diff --git a/build/debian/init-conda-env b/build/debian/init-conda-env
--- a/build/debian/init-conda-env
+++ b/build/debian/init-conda-env
@@ -4,58 +4,58 @@
 # ===========================================
 
 err_exit() {
-    echo "# !Error: $*"
-    exit 1
+	echo "# !Error: $*"
+	exit 1
 }
 
 # function to append text to a matched line number
 append_at_line_match() {
-    local pattern="$1"
-    local append="$2"
-    local file="$3"
-    local ln=$(awk -v pat="$pattern" '$0~pat{print NR}' "$file")
-    sed -i "$ln i $append" "$file"
+	local pattern="$1"
+	local append="$2"
+	local file="$3"
+	local ln=$(awk -v pat="$pattern" '$0~pat{print NR}' "$file")
+	sed -i "$ln i $append" "$file"
 }
 
 # function to create a new conda environment with mamba or conda from yaml file
 create_new_conda_env() {
-    set -e
-    export CONDA_ENV_FILE=${1:-/srv/conda/environment.yml}
-    [[ -f "${CONDA_ENV_FILE}" ]] ||
-        err_exit "env file does not exist: CONDA_ENV_FILE='$CONDA_ENV_FILE'"
+	set -e
+	export CONDA_ENV_FILE=${1:-/srv/conda/environment.yml}
+	[[ -f "${CONDA_ENV_FILE}" ]] ||
+		err_exit "env file does not exist: CONDA_ENV_FILE='$CONDA_ENV_FILE'"
 
-    # check that conda is installed
-    conda activate base >/dev/null
+	# check that conda is installed
+	conda activate base >/dev/null
 
-    # check if mamba is installed, else use conda
-    CONDA_CMD=mamba
-    command -v $CONDA_CMD &>/dev/null || CONDA_CMD=conda
-    conda info -a >"${HOME}/init-conda-env.log"
-    echo "# => Installing new conda virtual environment from $CONDA_ENV_FILE ..."
-    $CONDA_CMD env create -q --file "${CONDA_ENV_FILE}"
+	# check if mamba is installed, else use conda
+	CONDA_CMD=mamba
+	command -v $CONDA_CMD &>/dev/null || CONDA_CMD=conda
+	conda info -a >"${HOME}/init-conda-env.log"
+	echo "# => Installing new conda virtual environment from $CONDA_ENV_FILE ..."
+	$CONDA_CMD env create -q --file "${CONDA_ENV_FILE}"
 }
 
 # function to set CONDA_ENV_USER based on .yml environment file
 set_conda_env_user_from_file() {
-    local env_file="${1:-${CONDA_ENV_FILE}}"
-    export CONDA_ENV_USER=${CONDA_ENV_USER:-"base"}
-    if [[ -z "${CONDA_ENV_USER}" ]] || [[ "${CONDA_ENV_USER}" == "base" ]]; then
-        export CONDA_ENV_USER=$(awk '/name\:/ {print;}' "${env_file}" |
-            awk '{sub(/name\: /, "");} 1')
-        [[ -z "${CONDA_ENV_USER}" ]] && err_exit \
-            "Could not parse conda env name from file: $env_file"
-        echo "# => Setting CONDA_ENV_USER=${CONDA_ENV_USER} ..."
-        append_at_line_match "# <<< conda_base_debian <<<" \
-            "export CONDA_ENV_USER=${CONDA_ENV_USER}" "${HOME}/.bashrc"
-        append_at_line_match "# <<< conda_base_debian <<<" \
-            "export CONDA_ENV_USER=${CONDA_ENV_USER}" "${HOME}/.bash_profile"
-    fi
+	local env_file="${1:-${CONDA_ENV_FILE}}"
+	export CONDA_ENV_USER=${CONDA_ENV_USER:-"base"}
+	if [[ -z "${CONDA_ENV_USER}" ]] || [[ "${CONDA_ENV_USER}" == "base" ]]; then
+		export CONDA_ENV_USER=$(awk '/name\:/ {print;}' "${env_file}" |
+			awk '{sub(/name\: /, "");} 1')
+		[[ -z "${CONDA_ENV_USER}" ]] && err_exit \
+			"Could not parse conda env name from file: $env_file"
+		echo "# => Setting CONDA_ENV_USER=${CONDA_ENV_USER} ..."
+		append_at_line_match "# <<< conda_base_debian <<<" \
+			"export CONDA_ENV_USER=${CONDA_ENV_USER}" "${HOME}/.bashrc"
+		append_at_line_match "# <<< conda_base_debian <<<" \
+			"export CONDA_ENV_USER=${CONDA_ENV_USER}" "${HOME}/.bash_profile"
+	fi
 
-    # check that environment activates
-    conda activate ${CONDA_ENV_USER} >/dev/null
-    echo "----${CONDA_ENV_USER}----" >>"${HOME}/init-conda-env.log"
-    conda info -a >>"${HOME}/init-conda-env.log"
-    conda env export -f "${HOME}/${CONDA_ENV_USER}.lock.yml" --no-builds -q
+	# check that environment activates
+	conda activate ${CONDA_ENV_USER} >/dev/null
+	echo "----${CONDA_ENV_USER}----" >>"${HOME}/init-conda-env.log"
+	conda info -a >>"${HOME}/init-conda-env.log"
+	conda env export -f "${HOME}/${CONDA_ENV_USER}.lock.yml" --no-builds -q
 }
 
 create_new_conda_env "${CONDA_ENV_FILE}"
diff --git a/build/debian/init-env b/build/debian/init-env
--- a/build/debian/init-env
+++ b/build/debian/init-env
@@ -3,35 +3,40 @@
 # New User/Apt/Conda Env Initialization
 # =====================================
 
+err_exit() {
+	echo "# !Error: $*"
+	exit 1
+}
+
+if [[ ${#@} -gt 0 ]]; then
+	if [[ "$1" == "dev" ]]; then
+		args=(tail -f /dev/null)
+	else
+		args=("$@")
+	fi
+fi
+
 set -e
 init-apt-deps
 init-new-user
 
-_USER_INFO=$(cat /tmp/init-new-user.lastlog)
+_NEW_USER_FILE=/tmp/init-new-user.lastlog
+[[ ! -f ${_NEW_USER_FILE} ]] && err_exit "file '${_NEW_USER_FILE}'" \
+	"generated from 'init-new-user' script not found."
+_USER_INFO=$(cat ${_NEW_USER_FILE})
 export _USER_NAME=$(echo $_USER_INFO | cut -d: -f1)
 export _USER_GROUP=$(echo $_USER_INFO | cut -d: -f3)
 
 if [[ -z "${_USER_NAME}" ]]; then
-    echo "# ~Warning: user $_USER_NAME not found!"
-    if [[ ${#@} -gt 0 ]]; then
-        echo "running '$*' as '$(id -un)'"
-        if [[ "$1" == "dev" ]]; then
-            conda-run tail -f /dev/null
-        else
-            conda-run "$@"
-        fi
-    fi
-    exit 0
+	echo "# ~Warning: user $_USER_NAME not found!"
+	echo "running '$*' as '$(id -un)'"
+	exec conda-run "${args[@]}"
 fi
 
-sudo --preserve-env --set-home --non-interactive \
-    -u $_USER_NAME -g $_USER_GROUP bash -- <<EOF
-init-conda-env
-if [[ ${#@} -gt 0 ]]; then
-    if [[ "$1" == "dev" ]]; then
-        conda-run tail -f /dev/null
-    else
-        conda-run "$@"
-    fi
-fi
-EOF
+sudo --preserve-env --set-home --non-interactive -u $_USER_NAME -g $_USER_GROUP \
+	bash -c 'init-conda-env'
+
+exec sudo --preserve-env --set-home --non-interactive -u $_USER_NAME -g $_USER_GROUP \
+	bash -s "${args[@]}" <<-'EOF'
+		conda-run "$@"
+	EOF
diff --git a/build/debian/init-new-user b/build/debian/init-new-user
--- a/build/debian/init-new-user
+++ b/build/debian/init-new-user
@@ -4,8 +4,8 @@
 # =======================
 
 err_exit() {
-    echo "# !Error: $*"
-    exit 1
+	echo "# !Error: $*"
+	exit 1
 }
 
 _OUTPUT_FILE=/tmp/init-new-user.lastlog
@@ -18,14 +18,11 @@ ARG_NAME="${1:-${NEW_USER_NAME}}"
 ARG_GROUP="${2:-${NEW_USER_GROUP}}"
 ARG_UID=${3:-${NEW_USER_UID}}
 ARG_GID=${4:-${NEW_USER_GID}}
-ARG_TOSUDO="${5:-${NEW_USER_TOSUDO}}"
+ARG_SUDO="${5:-${NEW_USER_SUDO:-false}}"
 
 print_id() {
-    local _ARG_UID="$1"
-    local _ARG_NAME="$2"
-    local _ARG_GID="$3"
-    local _ARG_GROUP="$4"
-    echo "uid=${_ARG_UID}(${_ARG_NAME}) gid=${_ARG_GID}(${_ARG_GROUP})"
+	# uid username gid groupname
+	echo "uid=${1}(${2}) gid=${3}(${4})"
 }
 
 DEFAULT_NAME=${IMAGE_DEFAULT_USER_NAME:-$(id -un)}
@@ -37,7 +34,7 @@ DEFAULT_GID=$(id -g "${DEFAULT_NAME}" 2>/dev/null)
 [[ -z "${DEFAULT_GID}" ]] && DEFAULT_GID=$(id -g)
 
 echo "default user info ->" \
-    "$(print_id ${DEFAULT_UID} ${DEFAULT_NAME} ${DEFAULT_GID} ${DEFAULT_GROUP})"
+	"$(print_id ${DEFAULT_UID} ${DEFAULT_NAME} ${DEFAULT_GID} ${DEFAULT_GROUP})"
 
 # empty user name uses image default
 [[ -z "${ARG_NAME}" ]] && ARG_NAME=${DEFAULT_NAME}
@@ -58,18 +55,18 @@ ln -s /dev/null /var/log/faillog
 
 # add new group if new id specified
 if [[ ! ${ARG_GID} -eq ${DEFAULT_GID} ]]; then
-    [[ "${ARG_GROUP}" == "${DEFAULT_GROUP}" ]] && err_exit \
-        "group name '$ARG_GROUP' with gid '$ARG_GID' can't be the same as" \
-        "existing group: gid=${DEFAULT_GID}(${DEFAULT_GROUP})."
-    groupadd --gid ${ARG_GID} --force ${ARG_GROUP}
+	[[ "${ARG_GROUP}" == "${DEFAULT_GROUP}" ]] && err_exit \
+		"group name '$ARG_GROUP' with gid '$ARG_GID' can't be the same as" \
+		"existing group: gid=${DEFAULT_GID}(${DEFAULT_GROUP})."
+	groupadd --gid ${ARG_GID} --force ${ARG_GROUP}
 fi
 
 # add new user if not found
 if [[ ! $(id -u ${ARG_NAME} 2>/dev/null) ]]; then
-    echo "adding new user ->" \
-        "$(print_id ${ARG_UID} ${ARG_NAME} ${ARG_GID} ${ARG_GROUP})," \
-        "current user is $(id)"
-    useradd -u ${ARG_UID} -g ${ARG_GID} --no-log-init -ms /bin/bash ${ARG_NAME}
+	echo "adding new user ->" \
+		"$(print_id ${ARG_UID} ${ARG_NAME} ${ARG_GID} ${ARG_GROUP})," \
+		"current user is $(id)"
+	useradd -u ${ARG_UID} -g ${ARG_GID} --no-log-init -ms /bin/bash ${ARG_NAME}
 fi
 
 # actual group name and number assigned to new user
@@ -78,23 +75,24 @@ EST_NEW_GROUP_NAME=$(getent group ${ARG_GID} | cut -d: -f1)
 
 # overwrite groupname if different from specified
 if [[ ! "${EST_NEW_GROUP_NAME}" == "${ARG_GROUP}" ]]; then
-    ARG_GROUP=${EST_NEW_GROUP_NAME}
+	ARG_GROUP=${EST_NEW_GROUP_NAME}
 fi
 EST_NEW_GROUP_GID=$(getent group ${ARG_GROUP} | cut -d: -f3)
 
 # add user to all other groups
-usermod -a -G users,sudo,${DEFAULT_GROUP},${ARG_GROUP} ${ARG_NAME} 2>/dev/null
+usermod -a -G users,${DEFAULT_GROUP},${ARG_GROUP} ${ARG_NAME} 2>/dev/null
+
+# add sudo user
+if [[ "${ARG_SUDO}" = true ]]; then
+	usermod -a -G sudo ${ARG_NAME} 2>/dev/null
+	passwd -qd ${ARG_NAME} 2>/dev/null
+	echo '${ARG_NAME} ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers
+fi
 
 # workaround for 32-bit uid/gids for useradd, groupadd, usermod
 rm /var/log/lastlog /var/log/faillog
 touch /var/log/lastlog
 touch /var/log/faillog
-
-# add sudo user
-if [[ ! -z "${ARG_TOSUDO}" ]]; then
-    passwd -qd ${ARG_NAME} 2>/dev/null
-    echo '${ARG_NAME} ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers
-fi
 
 # username:uid:groupname:gid
 cat <<EOF >>$_OUTPUT_FILE
